python_hello

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,2 +1,18 @@
 #!/bin/bash
-python3 -c "import py_compile; py_compile.compile('$PYFILE', $'PYFILE' + 'c')"
+
+if [ -z "$PYFILE" ]; then
+	echo "Error: PYFILE environment variable is not set."
+	exit 1
+fi
+
+if [ ! -f "$PYFILE" ]; then
+	echo "Error: File $PYFILE not found."
+	exit 1
+fi
+
+filename=$(basename -- "$PYFILE")
+filename_no_ext="${filename%.*}"
+
+python -m py_compile "$PYFILE"
+mv "__pycache__/$filename_no_ext.cpython-*.pyc" "$filename_no_ext.c"
+echo "Compilation successful. Output filename: $filename_no_ext.c"
